### ISSUE TITLE
Confused by the switch to playlist view button

### ISSUE THREAD

**Issue by jrbastien** [fossfreedom/coverart-browser#356]
Hi fossfreedom,  I hope everything is well.
I have been doing some home renovation and did not have time to follow-up on this project progresses for a while.  I have one observation/suggestion if I may:

It took me a while to figure out that the vinyl icon was to switch to a play list view.  And given the coverart button is not at the same position, it took me some time to realize that it was simply bringing me back to the tile view.

Given the "..." are always present in any view, why not just adding a playlist entry in the dropdown menu after the play queue entry and removing these buttons?

This would also allow the interface to point to the right view because right now, it shows Tiles while it displays the play list view.

![playlist view](https://cloud.githubusercontent.com/assets/627071/6904972/848693e8-d6f2-11e4-818d-d7b6834de540.png)

**Comment by fossfreedom** [comment]
Hi @jrbastien 

  good to hear from you.  Hope its warming up in canada :)

Think you've spotted two issues here.  I'll have a look at these as part of the next release.

cheers

**Comment by fossfreedom** [comment]
ok - reworked all of this.  Should be resolved now.

**Comment by jrbastien** [comment]
Thanks for the changes.  That really looks better integrated now.  Only one little issue:  If you switch from playlist view to tiles view, the artist side pane always show up.
