### ISSUE TITLE
Can't run the plugin.

### ISSUE THREAD

**Issue by me4oslav** [fossfreedom/coverart-browser#357]
So, I wanted to go and improve the plugin design and after I compiled it and I try to run it I get:
(rhythmbox:21648): libpeas-WARNING **: Could not find plugin 'coverart_search_providers' for plugin 'coverart_browser'

**Comment by fossfreedom** [comment]
yep - as per the readme - you also need to install coverart-search-providers

 - https://github.com/fossfreedom/coverart-search-providers

**Comment by me4oslav** [comment]
Installed it, but when I start it I get:
Traceback (most recent call last):
  File "/home/me4oslav/.local/share/rhythmbox/plugins/coverart_search_providers/coverart_search_providers.py", line 29, in <module>
    from coverart_album_search import CoverAlbumSearch
  File "/home/me4oslav/.local/share/rhythmbox/plugins/coverart_search_providers/coverart_album_search.py", line 43, in <module>
    from coverart_search_tracks import mutagen_library
  File "/home/me4oslav/.local/share/rhythmbox/plugins/coverart_search_providers/coverart_search_tracks.py", line 28, in <module>
    from PIL import Image
ImportError: No module named 'PIL'

**Comment by fossfreedom** [comment]
on ubuntu the package is called python3-pil

Another fedora user said the equivalent python3 module is python3-pillow

 i.e.  sudo yum install git gettext python3-mako python3-requests python3-pillow python3-lxml

Have you got that installed?

**Comment by me4oslav** [comment]
Now it runs. Will have a look at the plugin, so I can see about the redesign. But it seems a large beast to tackle, so we might have to fix the sidebar first, which can be woeful.
Closing this issue.
