### ISSUE TITLE
Plugin Not Working

### ISSUE THREAD

**Issue by spikey-dino** [fossfreedom/coverart-browser#358]
Hi, I left comments on your blog and you asked me to put the errors here.

So when I run rhythmbox I get the following error:
(rhythmbox:15472): Gtk-CRITICAL **: gtk_css_provider_load_from_path: assertion 'path != NULL' failed

The plugin shows up in rhythmbox but when I click to enable an error symbol appears next to them.

**Comment by fossfreedom** [comment]
run 

    rhythmbox

in a terminal

then within rhythmbox activate the plugin.  There should be more output then displayed in your terminal.  Please can you copy-paste the new output here?

**Comment by spikey-dino** [comment]
(rhythmbox:18022): libpeas-WARNING **: Could not find loader 'python' for plugin 'coverart_search_providers'

**Comment by fossfreedom** [comment]
what is the contents of the following folder

    cd ~/.local/share/rhythmbox/plugins
    ls

?

**Comment by spikey-dino** [comment]
In cd ~/.local/share/rhythmbox/plugins  there are two folders

coverart_browser , coverart_search_providers

**Comment by fossfreedom** [comment]
you probably have manually installed the plugin in the past

Since you are now using the PPA - please delete these two folders.  These are not needed and are confusing ubuntu

**Comment by spikey-dino** [comment]
I deleted the folders and restarted -- it  fixed the problem :)

Thank you so much!  I love your plugin
