### ISSUE TITLE
[DESIGN] Coverart mode toggling.

### ISSUE THREAD

**Issue by me4oslav** [fossfreedom/coverart-browser#359]
Currently how one toggles the coverart if from the sidebar. It is a menu hosted under library category in the sidebar. However the sidebar hosts sources (both offline and online) and playlists and not view modes and the coverart is by every aspect a view mode.
What hosts the views is the headerbar, so it only makes sense for the headerbar to host the coverart too. 
Hence I created this design to toggle the coverart:
![screenshot from 2015-04-05 14 58 01](https://cloud.githubusercontent.com/assets/1658870/6996757/38c83f7c-dba4-11e4-8313-3aa1dca7fd2f.png)
Tell me what what you think.
Needless to say we can have any symbolic icon for it, I just quickly scrapped up one.

**Comment by fossfreedom** [comment]
I think it should be possible to replace the sources list with the list in the "..." button.  I'll have a look.

Remember that side pane can display more than just the current sources - Click View - Play Queue in Side Pane.  Thus I assume we are not changing this - just the scrolled window section of the side pane hosting the list of sources?

Let me get this correct in my understanding.  You click "Categories" in any source - when you do this the two toggle buttons on the left hand side become visible.  Clicking Songs hides these toggle buttons.

If you are in the CoverArt browser plugin - clicking Songs switches automatically back to the Music Library source ... turns off the left hand side toggle buttons and replaces the "coverart view" back to the standard sources view.  Correct?

At the moment, we hide "Song-Categories" for the sources that you cannot "Browser" - i.e. Play Queue, LastFM, LibreFM (and in Rhythmbox 3.2) the SoundCloud plugin.  So - is the intention here to always display "songs and categories" - even if the categories option doesnt actually do anything for the source?

**Comment by me4oslav** [comment]
It goes like this - the left hand toggles should always be there, but active or inactive depending on whether they are needed or not. UI elements that appear or disappearare not Gnome HIG friendly simply because UI psychology 101 - they stress people. Greying out (making inactive) is less stressful.
Now - the toggles should be active If you are in source that allow coverview (lets say local library, which allows that) and you're in Categories view.  The text icon on the left toggles (left icon) transfer you to normal text categories view, the right icon of the left toggles (we can do any symbolic icon we like, the one I did was scrapped up for a min, so we can change) transfers you to coverview mode. For any other cases that left set of toggles should be inactive. Have it active only when it is useful
Regarding making the <Songs | Categories > toggle go away - nah, they should just get inactive for cases where they are not needed - like last.fm for example. Making elements go away causes extra stress in the users minds. :)
That would be all, did you get it?
P.S. Do you want me to change the coverart symbolic that I made? The rationale behind is a single cover plus two more on its sides. But I can do another icon if you don't like that one. Symbolics are super easy for me to do.

**Comment by fossfreedom** [comment]
yep - I think I get where you are going.

So - you've toggled to "CoverView" - what do you actually see in the left hand pane?

![pic](http://i.imgur.com/VskjJIH.png)

CoverArt Browser consists of 3 views.  The last two are links to the standard rhythmbox Play Queue and Music Library sources.

Or were you thinking of adding the various picture filter options available?

![pic](http://i.imgur.com/8prDuY1.png)

**Comment by me4oslav** [comment]
I am yet to get to redesigning the cover art view. That will take time. But I will do it. :)
Let's first see this bug fixed.

**Comment by me4oslav** [comment]
I need to know - do you want me to do another symbolic icon for the coverart or send you the one that I used on the wireframe?

**Comment by fossfreedom** [comment]
if you can dropbox me the two symbolic icons used, I'll add it to the master branch.

Thanks.

**Comment by me4oslav** [comment]
The first is standard symbolic icon. :) "view-list-symbolic.svg"
Here is the custom one:
https://www.dropbox.com/s/997jmkr30ervio7/view-cover-symbolic.svg?dl=0
Make sure the plugin puts it in /usr/share/icons/Adwaita/scalable/actions/ with the file name I've used, because that's what XDG specs say. Don't wanna break them. :P

**Comment by fossfreedom** [comment]
if I place that icon into the Adwaita folder then no other theme will be able to access this unless the Adwaita theme is itself installed.

For the moment I've just added this to the img sub-folder of coverart-browser.

The above commit (on the master branch) shows the header switcher in action.  I havent as yet hooked up the coverart view when you click on the views.  

Is this the sort of thing you were envisaging with this change?

**Comment by me4oslav** [comment]
I just pulled the latest coverart plugin and executed "./install.sh". It installed properly, but what I get is sidebar button and not toggle in the headerbar?
![screenshot from 2015-04-07 00 28 44](https://cloud.githubusercontent.com/assets/1658870/7012902/73fc50a0-dcbd-11e4-95b5-4fb8d82952f7.png)
Am I doing something wrong?

**Comment by fossfreedom** [comment]
should have said - make sure you are fully up-to-date with alternative-toolbar as well - there is a tweak needed which I pushed earlier.

**Comment by me4oslav** [comment]
With both latest alternative-toolbar and covert installed and enabled.
![screenshot from 2015-04-07 00 52 15](https://cloud.githubusercontent.com/assets/1658870/7013261/702b4f14-dcc0-11e4-9189-db8484fe74d1.png)
It hates me. :(

**Comment by fossfreedom** [comment]
and you are using the master branch of coverart-browser?

    git checkout master

**Comment by me4oslav** [comment]
Yup, I am using the master branch.

**Comment by fossfreedom** [comment]
hmm.

   what is the output of

    rhythmbox -D coverart

?

**Comment by me4oslav** [comment]
I will tell you in the morning. I am now in bed, because the zillions of sedatives I drank finally kicked in and ... well, I am extremely sleepy now.

**Comment by fossfreedom** [comment]
ok - sleep tight.  When you next read this, please git pull origin master to get the very latest - I've put some more trace statements for me to narrow down your issue.  Thanks.

**Comment by me4oslav** [comment]
AFter installing the latest master and executing "rhythmbox -D coverart":

[me4oslav@localhost coverart-browser]$ rhythmbox -D coverart

(rhythmbox:3048): Gtk-WARNING **: Failed to register client: GDBus.Error:org.gnome.SessionManager.AlreadyRegistered: Unable to register client

(rhythmbox:3048): libsoup-CRITICAL **: soup_server_quit: assertion 'priv->listeners != NULL' failed
sys:1: Warning: object SoupServer 0x29a44e0 finalized while still in-construction
sys:1: Warning: Custom constructor for class SoupServer returned NULL (which is invalid). Please use GInitable instead.
(11:41:38) [0x17a2e60] [CoverArtAlbumSearchPlugin.do_activate] /home/me4oslav/.local/share/rhythmbox/plugins/coverart_search_providers/coverart_search_providers.py:174: CoverArtBrowser DEBUG - do_activate
(11:41:38) [0x17a2e60] [CoverArtAlbumSearchPlugin.do_activate] /home/me4oslav/.local/share/rhythmbox/plugins/coverart_search_providers/coverart_search_providers.py:195: CoverArtBrowser DEBUG - end do_activate
(11:41:38) [0x17a2e60] [CoverArtBrowserPlugin.do_activate] /home/me4oslav/.local/share/rhythmbox/plugins/coverart_browser/coverart_browser.py:135: CoverArtBrowser DEBUG - do_activate
(11:41:38) [0x17a2e60] [CoverArtBrowserSource._connect_properties] /home/me4oslav/.local/share/rhythmbox/plugins/coverart_browser/coverart_browser_source.py:180: CoverArtBrowser DEBUG - _connect_properties
(11:41:38) [0x17a2e60] [CoverArtBrowserSource._connect_properties] /home/me4oslav/.local/share/rhythmbox/plugins/coverart_browser/coverart_browser_source.py:189: CoverArtBrowser DEBUG - end _connect_properties
(11:41:38) [0x17a2e60] [_impl.__init__] /home/me4oslav/.local/share/rhythmbox/plugins/coverart_browser/coverart_browser_source.py:2468: OrderedDict([('coverview', ['Tiles', GLib.Variant('s', 'coverart-browser-tile')]), ('coverflowview', ['Flow', GLib.Variant('s', 'coverart-browser-coverflow')]), ('artistview', ['Artist', GLib.Variant('s', 'coverart-browser-artist')]), ('listview', ['Music', GLib.Variant('s', 'coverart-browser-list')]), ('queueview', ['Play Queue', GLib.Variant('s', 'coverart-browser-queue')])])
(11:41:38) [0x17a2e60] [CoverArtBrowserPlugin.do_activate] /home/me4oslav/.local/share/rhythmbox/plugins/coverart_browser/coverart_browser.py:174: CoverArtBrowser DEBUG - end do_activate

(rhythmbox:3048): Gtk-WARNING **: Failed to set property GtkButtonBox.layout-style to : Could not parse enum: `'

(rhythmbox:3048): Gtk-WARNING **: Failed to set property GtkButtonBox.layout-style to : Could not parse enum: `'

(rhythmbox:3048): Gtk-WARNING **: Failed to set property GtkButtonBox.layout-style to : Could not parse enum: `'

(rhythmbox:3048): Gtk-WARNING **: Failed to set property GtkButtonBox.layout-style to : Could not parse enum: `'

(rhythmbox:3048): Gtk-WARNING **: Duplicate child name in GtkStack: Add to Playlist


(rhythmbox:3048): Gtk-WARNING **: Duplicate child name in GtkStack: Add to Playlist


(rhythmbox:3048): Gtk-WARNING **: Duplicate child name in GtkStack: Add to Playlist


(rhythmbox:3048): Gtk-WARNING **: Duplicate child name in GtkStack: Add to Playlist


(rhythmbox:3048): Gtk-WARNING **: Duplicate child name in GtkStack: Add to Playlist


(rhythmbox:3048): Gtk-WARNING **: Duplicate child name in GtkStack: Add to Playlist

**Comment by fossfreedom** [comment]
Hi - 

 the trace is definitely missing the debug statements I added

https://github.com/fossfreedom/coverart-browser/commit/3baac6bf26169311f18680f87027e7d995817306

if you look at coverart_browser.py - please can you let me know if those extra lines added in the commit are in your version that you've checked out of the master stream.  Thanks

Can you  double check that in the folder ~/.local/share/rhythmbox/plugins that you dont have two or more sub-folders that have the file coverart_browser.plugin in those sub-folders - i.e. there should only be one subfolder called coverart_browser and coverart_browser.plugin is a file within this.

**Comment by me4oslav** [comment]
What the fsck. It started working out of the blue. :D
I dunno why it didn't work before.
Anyways what I get now is this:
![screenshot from 2015-04-07 13 58 37](https://cloud.githubusercontent.com/assets/1658870/7021818/51b925d8-dd2e-11e4-8b45-c1b69b370fb3.png)
Aside from the hooking bug there are more issues:
  -  The padding should be as same as the padding on the bottom play bar;
  -  The toggle should be disabled in Songs mode;
  -  The custom symbolic icon should get coloured by the GTK theme;

**Comment by fossfreedom** [comment]
ok - excellent news

Anyway - apart from the above - the toggling from sources view to the coverart list - is this part of your vision as currently implemented or were you expecting more than just the GtkTreeView list as shown?

**Comment by me4oslav** [comment]
Apart from the issues I outlined above - it is fine. Mind you, there are lots of issues above, so ... :P

**Comment by fossfreedom** [comment]
minor ... minor ... :)

ok - I'll tidy this up this week.

**Comment by me4oslav** [comment]
Good. I will try to start on coverart design, but it will take me a while. I need to get familiar with the plugin first. The thing is a huge beat to tackle. Oh and - http://www.webupd8.org/2015/04/enable-client-side-decorations-for.html

**Comment by fossfreedom** [comment]
a few comments.

I cannot delete coverart browser from the standard source list in the sidebar.  That will have to wait for the sources redesign.

I'm using a standard Gtk.StackSwitcher.  Doesnt appear to have any ability to "pad" this widget - or at least I havent a clue how to-do this.  The sizing for each switcher button looks identical to the search button anyway.

One minor issue remains I think - the automatic highlighting of which coverview you are on when first activated.

Other than that - have a play - let me know what you think.

N.B. as before - get the latest tweaks to alternative-toolbar as well as the latest master branch of coverart-browser.

**Comment by me4oslav** [comment]
Sources redesign? Is that the sidebar redesign?
There is a tiny bug - if I enable the coverart and then go back to Songs view, the toggle gets inactive - which is OK. But it also default back to list view, so next time I go back to Categories I am in text view and not in coverart view.

**Comment by fossfreedom** [comment]
Yep ... Sources is rhythmbox term for the sidebar.

I thought it was more logical for going back to the list of songs if you click songs.  What did you think should happen?  If you go to songs but then wanted to filter on those songs you couldn't because the toggle is inactive.  Maybe leave the toggle enabled ... So if you wanted to filter on songs you have to toggle back to sources before clicking categories.  Does this sound OK?

 We don't use tooltips anywhere else.  Should we ... If so what buttons?

**Comment by me4oslav** [comment]
Man, I suck at API language. When I write Gnome-Shell CSS I still wonder why the dock uses .dash class. When I get derpy I even try to theme the not existing .dock class. :P Anyways, I guess we should first tackle the sidebar redesign implementation, because coverart one would be much bigger of a beast. Plus sidebar redesign is very much done, so there is that.

The toggle should not change what is selected and what is not when the user goes back to a vew that does not support coverart. If it categories mode it is left at coverart mode when going back to songs mode it should become inactive - yes, but the selected toggle should remain coverart.

Regarding tooltips - Gnome HIG says - tooltips on all the buttons. Guess we should add such to not break it.

**Comment by fossfreedom** [comment]
ok - looks like there is a Gtk bug where stackswitcher does not allow tooltips.

Lets raise a separate issue for tooltips in general.  I'm a little dubious because I added tooltips for the playcontrols and it became quickly irritating to see tooltips appearing for such common buttons.  Not sure if you can set the delay of tooltips - but we need to be very careful adding tooltips where they can become more of a distraction/irritation rather than being useful.

Anyway - finished the implementation here.  Looks ok to me.

**Comment by me4oslav** [comment]
For some reason now there seems to be a bug with the implementation. If I go back in songs view the left toggle is still active:
![screenshot from 2015-04-09 11 11 09](https://cloud.githubusercontent.com/assets/1658870/7062774/35d2854a-dea9-11e4-9c08-131b3a582e61.png)
On which repo should I open the tooltips bug?

**Comment by fossfreedom** [comment]
Actually - that was deliberate - rational - we are in coverart mode at this point.  

So Songs (&Categories) is just a view like other views and is part of coverart mode.  When you go to listview - then songs becomes part of that new mode and then the switcher becomes disabled.

Does feel more natural to use.

Tooltips should be on the alternative-toolbar project.
