### ISSUE TITLE
Incompatible with rhythmbox-plugin-llyrics

### ISSUE THREAD

**Issue by StephGbzh** [fossfreedom/coverart-browser#362]
I have been using Rhythmbox (from Ubuntu repo) for several years with many plugins, including this one (from the ppa) but today it froze at startup after a few seconds. Coverart_browser had just enough time to kick in and display its usual consecutive loading bars on the bottom right of the window but just before finishing the last one, it stopped and Rhythmbox would freeze, becoming grey all over and totally unresponsive.

Using this info:
https://wiki.gnome.org/Apps/Rhythmbox/FAQ#Where_does_Rhythmbox_store_its_data_.3F
I renamed both folders to
${HOME}/.local/share/rhythmboxOld and ${HOME}/.cache/rhythmboxOld
and relaunched Rhythmbox: nothing changed, same freeze at the same step.

Launching with "rhythmbox -d" showed many strange logs about Pipelight so I looked for info and found your question to the pipelight guys https://answers.launchpad.net/pipelight/+question/260874

So next I uninstalled everything Rhythmbox related, plugins and all, added your other ppa (ppa:fossfreedom/rhythmbox) to get the last Rhythmbox version and reinstalled everything.
Result: no more Pipelight errors but still the exact same freeze, aaarggh!

At last I looked at the help page https://github.com/fossfreedom/coverart-browser/wiki/Resolving-issues and started messing with plugins, noting that a bare Rhythmbox works (hurrah, I can listen to Music at least!).

And finally here it is: rhythmbox-plugin-coverart-browser and rhythmbox-plugin-llyrics from ppa:fossfreedom/rhythmbox-plugins are incompatible and cause the above freeze when both are activated, at least on my machine.

Could you try to fix it please ?
For now, I uninstalled the lyrics plugin as I cannot even deactivate it due to the freeze...

**Comment by fossfreedom** [comment]
Hi,
  think your issue is probably this one

 - https://github.com/fossfreedom/coverart-browser/issues/342

This is a bug in the lyrics plugin - it is holding onto threads when it shouldnt do - and since coverart browser also uses threads there is a lockup issue.  The real fix should actually be on the lyrics plugin.

In the above issue I reworked this bit of the code to not use threads.  This fix is on the master branch - the current development branch.

Suggest try the master branch to see if this is really your issue or if there is another lockup issue here.

**Comment by StephGbzh** [comment]
Thanks, the master branch works along the lyrics plugin !

**Comment by fossfreedom** [comment]
ok - excellent news.

I'll close this then.  

Remember - you'll need to regularly install the master branch with updates yourself because installing manually overrides the PPA package.

I havent finalised a date for the next release yet, probably later this year depending upon progress being made.
