### ISSUE TITLE
Multiple views of the same album with diferent authors

### ISSUE THREAD

**Issue by DFOXpro** [fossfreedom/coverart-browser#372]
If you have an album that have multiple authors (Like https://en.wikipedia.org/wiki/One_World_One_Voice) you get an "album" display per song:
![captura de pantalla de 2015-10-13 10 10 31](https://cloud.githubusercontent.com/assets/5248241/10458982/12eb2f46-7193-11e5-9371-5fcc5c74c67a.png)

Expected behavior: just one display of the entire album.

**Comment by fossfreedom** [comment]
actually this is a duplicate - it is simple to resolve.

By default rhythmbox does not treat "various artist" albums very well - as you notice, you see one album cover per artist.

We have overcome this issue by using the "Album Artist" field - if filled then the artists of an album are correctly pulled together under one cover.

CTRL+Click each album cover you see for every track of the album. Right click and choose properties. Fill in the album artist field and then click OK. The cover view will then show all the tracks under one cover.

    https://github.com/fossfreedom/coverart-browser/wiki/how-to-for-version-2.x

look for the "hint - Select multiple albums - change both the album name and album artist and all the tracks for the selected albums will be combined under one album."
