### ISSUE TITLE
Update PPA build for Wily

### ISSUE THREAD

**Issue by mjog** [fossfreedom/coverart-browser#373]
Changes for Rhythmbox 3.2 compatibility (e.g 58339c7) seem to be in the repo but not included in the debs generated by the PPA for Wily (which ships RB 3.2).

Can the PPA get updated to include these? Ta!

**Comment by fossfreedom** [comment]
good point well made!

I'll have a quick look through and cherry-pick the appropriate commits.  Will let you know when done.

**Comment by fossfreedom** [comment]
@mjog - I just looked at the wily deb file - that commit you've pointed me at is already in the deb - /usr/lib/rhythmbox/plugins/coverart_browser/coverart_browser.py

Have you got a local copy hiding the system install?  ~/.local/share/rhythmbox/plugins/coverart_browser

**Comment by mjog** [comment]
Oh, you're totally right. That was weird, I must have copied and pasted the path from RB's debug log assuming it was in /usr. Apologies for the noise.
