### ISSUE TITLE
Add a "Show in folder" option in contextual menu

### ISSUE THREAD

**Issue by strycore** [fossfreedom/coverart-browser#374]
I love the cover art browser, it made me switch from Banshee back to Rhythmbox but there's one feature I miss a lot from Banshee. It's the ability to open the folder containing a track by selecting a "Show in folder" action in the contextual menu. I use this a lot when I need to retag tracks in Picard for example.

Many Gnome programs provide this option (evince, shotwell, shutter) and I'd love to see it in Rhythmbox as well. If you lack the time to implement this, I could have a shot a it, I've already implemented such things in Lutris with uses Python and PyGObject as well.

**Comment by fossfreedom** [comment]
if you use this plugin then it should also appear in the coverart context menu as well.

 - https://github.com/donaghhorgan/rhythmbox-plugins-open-containing-folder

**Comment by strycore** [comment]
Thanks! That's great, it's exactly what I was looking for :)
