### ISSUE TITLE
[question, suggestion, no issue] How to jump to "playing title"

### ISSUE THREAD

**Issue by careca1970** [fossfreedom/coverart-browser#378]
Hi, I wonder on how to fastly jump to playing title by clicking on an icon/button.
As by old stile (music list), if you click on the "speaker icon" (top-left, first column, of the list) it will jump to the actually playing title...

Maybe it is not the common way to use cover-browser, but I very often start playing by choosing "play random album title" from the menu.
During playback, I use to scroll through other albums, and can't find a way to go back to the one actually playing.
Maybe a suggestion...

Thank you for good work!

**Comment by fossfreedom** [comment]
Hi - the shortcut CTRL+J will jump to the playing album.

Is that what you are referring to?

**Comment by careca1970** [comment]
Hi! 
Thanks, it works.
I will pay more attention on shortcuts from now on.
Luckily there is a list of all shortcuts under help.

**Comment by fossfreedom** [comment]
excellent!
