### ISSUE TITLE
After update to Fedora23/Gnome desktop, Coverart-browser Toolbar buttons broken

### ISSUE THREAD

**Issue by careca1970** [fossfreedom/coverart-browser#381]
I have been using Rhythmbox on Fedora up to 22 and Coverart-browser without problems.
After upgrading to Fedora23, I noticed that pressing "some" of the Coverart-browser makes Rhythmbox strangely stop being managed by Gnome. Rhythmbox continues with full functionality, but Gnome does not "see" it any more. (i.e. Rhythmbox can't be focussed by means of "Alt-Tab")

Here the output from the shell. Maybe the last lines may give an answer to my problem:

$ rhythmbox

(rhythmbox:12214): libsoup-CRITICAL **: soup_server_quit: assertion 'priv->listeners != NULL' failed
sys:1: Warning: object SoupServer 0x55dd4cc27c40 finalized while still in-construction
sys:1: Warning: Custom constructor for class SoupServer returned NULL (which is invalid). Please use GInitable instead.
/home/Alex/.local/share/rhythmbox/plugins/coverart_browser/coverart_widgets.py:26: PyGIWarning: Notify was imported without specifying a version first. Use gi.require_version('Notify', '0.7') before import to ensure that the right version gets loaded.
  from gi.repository import Notify
/home/Alex/.local/share/rhythmbox/plugins/coverart_browser/coverart_covericonview.py:28: PyGIWarning: PangoCairo was imported without specifying a version first. Use gi.require_version('PangoCairo', '1.0') before import to ensure that the right version gets loaded.
  from gi.repository import PangoCairo
/home/Alex/.local/share/rhythmbox/plugins/coverart_browser/coverart_artistinfo.py:28: PyGIWarning: WebKit was imported without specifying a version first. Use gi.require_version('WebKit', '3.0') before import to ensure that the right version gets loaded.
  from gi.repository import WebKit

(rhythmbox:12214): Gtk-WARNING **: Duplicate child name in GtkStack: Zur Wiedergabeliste hinzufügen

(rhythmbox:12214): Gtk-WARNING **: Duplicate child name in GtkStack: Zur Wiedergabeliste hinzufügen

(rhythmbox:12214): Gtk-WARNING **: Duplicate child name in GtkStack: Zur Wiedergabeliste hinzufügen

(rhythmbox:12214): Gtk-WARNING **: Duplicate child name in GtkStack: Zur Wiedergabeliste hinzufügen

(rhythmbox:12214): Gtk-WARNING **: Duplicate child name in GtkStack: Zur Wiedergabeliste hinzufügen

(rhythmbox:12214): Gtk-WARNING **: Duplicate child name in GtkStack: Zur Wiedergabeliste hinzufügen

(rhythmbox:12214): Gtk-CRITICAL **: gtk_box_reorder_child: assertion 'old_link != NULL' failed
openjdk version "1.8.0_72"
OpenJDK Runtime Environment (build 1.8.0_72-b16)
OpenJDK 64-Bit Server VM (build 25.72-b16, mixed mode)

(rhythmbox:12214): Gtk-WARNING **: Duplicate child name in GtkStack: Zur Wiedergabeliste hinzufügen

(rhythmbox:12214): Gtk-WARNING **: Duplicate child name in GtkStack: Zur Wiedergabeliste hinzufügen

(rhythmbox:12214): Gtk-WARNING **: Duplicate child name in GtkStack: Zur Wiedergabeliste hinzufügen

(rhythmbox:12214): Gtk-WARNING **: Duplicate child name in GtkStack: Zur Wiedergabeliste hinzufügen

(rhythmbox:12214): Gtk-WARNING **: Duplicate child name in GtkStack: Zur Wiedergabeliste hinzufügen

(rhythmbox:12214): Gtk-WARNING **: Duplicate child name in GtkStack: Zur Wiedergabeliste hinzufügen

(rhythmbox:12214): Gtk-WARNING **: Duplicate child name in GtkStack: Zur Wiedergabeliste hinzufügen

(rhythmbox:12214): Gtk-WARNING **: Duplicate child name in GtkStack: Zur Wiedergabeliste hinzufügen

(rhythmbox:12214): Gtk-WARNING **: Duplicate child name in GtkStack: Zur Wiedergabeliste hinzufügen

(rhythmbox:12214): Gtk-WARNING **: Duplicate child name in GtkStack: Zur Wiedergabeliste hinzufügen

(rhythmbox:12214): Gtk-WARNING **: Duplicate child name in GtkStack: Zur Wiedergabeliste hinzufügen

(rhythmbox:12214): Gtk-WARNING **: Duplicate child name in GtkStack: Zur Wiedergabeliste hinzufügen

(rhythmbox:12214): Gtk-WARNING **: Duplicate child name in GtkStack: Zur Wiedergabeliste hinzufügen

(rhythmbox:12214): Gtk-WARNING **: Duplicate child name in GtkStack: Zur Wiedergabeliste hinzufügen

(rhythmbox:12214): Gtk-WARNING **: Duplicate child name in GtkStack: Zur Wiedergabeliste hinzufügen

(rhythmbox:12214): Gtk-WARNING **: Duplicate child name in GtkStack: Zur Wiedergabeliste hinzufügen

(rhythmbox:12214): Gtk-WARNING **: Duplicate child name in GtkStack: Zur Wiedergabeliste hinzufügen

(rhythmbox:12214): Gtk-WARNING **: Duplicate child name in GtkStack: Zur Wiedergabeliste hinzufügen

(rhythmbox:12214): Gtk-WARNING **: Duplicate child name in GtkStack: Zur Wiedergabeliste hinzufügen

(rhythmbox:12214): Gtk-WARNING **: Duplicate child name in GtkStack: Zur Wiedergabeliste hinzufügen

(rhythmbox:12214): Gtk-WARNING **: Duplicate child name in GtkStack: Zur Wiedergabeliste hinzufügen

(rhythmbox:12214): Gtk-WARNING **: Duplicate child name in GtkStack: Zur Wiedergabeliste hinzufügen

(rhythmbox:12214): Gtk-WARNING **: Duplicate child name in GtkStack: Zur Wiedergabeliste hinzufügen

(rhythmbox:12214): Gtk-WARNING **: Duplicate child name in GtkStack: Zur Wiedergabeliste hinzufügen

(rhythmbox:12214): Gtk-WARNING **: Duplicate child name in GtkStack: Zur Wiedergabeliste hinzufügen

(rhythmbox:12214): Gtk-WARNING **: Duplicate child name in GtkStack: Zur Wiedergabeliste hinzufügen

(rhythmbox:12214): Gtk-WARNING **: Duplicate child name in GtkStack: Zur Wiedergabeliste hinzufügen

(rhythmbox:12214): Gtk-WARNING **: Duplicate child name in GtkStack: Zur Wiedergabeliste hinzufügen

sys:1: Warning: invalid (NULL) pointer instance
sys:1: Warning: g_signal_handlers_disconnect_matched: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed
sys:1: Warning: g_object_unref: assertion 'G_IS_OBJECT (object)' failed

**Comment by fossfreedom** [comment]
Those just look like warnings. Doubtful they are the cause of your issue.  

You could have a go and add those gi.require version statements to see if things improve

Sorry I don't use fedora ... I haven't seen this on Ubuntu 16.04 which I believe use similar libraries.



You could try adding those

**Comment by careca1970** [comment]
I'm closing the issue, since I had too many peoblems after my upgrade to FC23.
Problems with Rhythmbox were just some among many others.
I suspect that I have anything broken with regard to GTK. Already FC22 behaves sometimes strange.
I have been upgrading this same installation since FC17...
I will plan to make a fresh install of FC23 or many FC24. Then I don't expect having any further problems with Coverart-browser.
Many thanks and keep the nice work!
