### ISSUE TITLE
missing webkit dependency on 16.04

### ISSUE THREAD

**Issue by fossfreedom** [fossfreedom/coverart-browser#383]
gir1.2-webkit-3.0 is missing from the dependency list

This SHOULD NOT be added though since webkit is security vulnerable but more importantly causes rhythmbox to crash when activated #382 

Need to disable sections of code  that depend on webkit.

Also - GTK3.18 has changed how size-allocate functions work causing stuff to not space correctly.

**Comment by DragoonZ** [comment]
I installed gir1.2-webkit-3.0 and it's still crashing

**Comment by fossfreedom** [comment]
@DragoonZ - as I said above ... it SHOULD NOT be installed.

I've created a new branch (commit) about that resolves the immediate crash.

However, as I said above GTK3.18 has broken the plugin - there are size-allocation issues when running that needs to be fixed.

**Comment by fossfreedom** [comment]
fundamentally gtk3.18 broke the plugin - closing similar issues and consolidating as this https://github.com/fossfreedom/coverart-browser/issues/387
