### ISSUE TITLE
Update so that it works with Rhythmbox 3.4.1

### ISSUE THREAD

**Issue by latach** [fossfreedom/coverart-browser#394]
Could you please update the plugin so that it works with Rhythmbox 3.4.1?

**Comment by fossfreedom** [comment]
I'm open to offers of help - however, my priorities are elsewhere at the moment.  Sorry.

**Comment by latach** [comment]
My issue was as you can see in this snapshot:
![screenshot - 20170913 - 14 58 47](https://user-images.githubusercontent.com/21196400/30381627-d7146b6a-9894-11e7-9ffc-1952f62e11d6.png)

I fixed it by installing gir1.2-webkit-3.0

I think it should be added to the dependencies. Thank you!
