### ISSUE TITLE
Doesn't work in Pop!_OS 19.04

### ISSUE THREAD

**Issue by davidrhoderick** [fossfreedom/coverart-browser#401]
So I'd really like this support in Rhythmbox but I can't get the plugin to work.  I tried to download all the necessary packages via apt-get but run into an issue with `gir1.2-webkit-3.0`.  Then I tried to install via the git repo anyways and I get the following output:

    installing languages to /usr/share/locale/
    installing en_US
    en_US.po:13: warning: header field 'Language-Team' still has the initial default value
    Installing the glib schema (password needed)

I tried it both as sudo and without (since "password needed" made me think it should be installed with sudo).  And when I turn it on in Rhythmbox, I just get an error icon and nothing else.  Here is my system info:

- Pop!_OS 19.04 (similar to Ubuntu)
- Rhythmbox 3.4.3

Not sure if you need any other specs but I can provide them.  Also, if there is a log I can provide, let me know where to find it.  Thanks for this plugin!

**Comment by srj-github** [comment]
same here, have you managed to make it work?

**Comment by davidrhoderick** [comment]
Nope, tried it just now and it looks like no one is really working on this project anymore...

**Comment by ghost** [comment]
Vou falar em portugues mesmo. hehehe

eu consegui fazer funcionaaarrr.. ta MUITO SHOWWW!! vejam

![Captura de tela de 2020-08-18 00-26-47](https://user-images.githubusercontent.com/2234645/90467056-c0db4080-e102-11ea-9f83-777aebed2990.png)

eu consegui no PureOS (Debian 100% livre). o que eu fiz foi apenas instalar manualmente o pacote gir1.2-webkit-3.0 e suas dependencias.

eu baixei por aqui:  https://packages.debian.org/stretch/amd64/gir1.2-webkit-3.0/download

e instalei assim

sudo dpkg -i gir1.2-webkit-3.0_2.4.11-3_amd64.deb

tem as dependencias tbm q seguem a mesma parada.
