### ISSUE TITLE
password needed?

### ISSUE THREAD

**Issue by huguitovi** [fossfreedom/coverart-browser#402]
I can't get it to work. After downloading from Githhub:

~/coverart-search-providers$ ./install.sh -rb3
installing languages to /usr/share/locale/
installing es
Installing the glib schema (password needed)

debian10@debian10:~/coverart-browser$ ./install.sh
installing languages to /usr/share/locale/
installing es
Installing the glib schema (password needed)

I've already installed all the necessary packages. But it still doesn't work. I'm on Debian 10. Rhythmbox 3.4.3 

![Captura de pantalla de 2020-07-21 15-18-13](https://user-images.githubusercontent.com/52084755/88091475-77c8b880-cb65-11ea-83d6-073bbc74c815.png)

**Comment by mmgoilf** [comment]
Same problem here, also on Debian 10. Anybody know a solution? Honestly this should be a default feature in rhythmbox, why did they have to make the album art so small? I think album artwork is a essential part of an album's experience.

**Comment by ghost** [comment]
Vou falar em portugues mesmo. hehehe

eu consegui fazer funcionaaarrr.. ta MUITO SHOWWW!! vejam

![Captura de tela de 2020-08-18 00-26-47](https://user-images.githubusercontent.com/2234645/90467056-c0db4080-e102-11ea-9f83-777aebed2990.png)

eu consegui no PureOS (Debian 100% livre). o que eu fiz foi apenas instalar manualmente o pacote gir1.2-webkit-3.0 e suas dependencias.

eu baixei por aqui:  https://packages.debian.org/stretch/amd64/gir1.2-webkit-3.0/download

e instalei assim

sudo dpkg -i gir1.2-webkit-3.0_2.4.11-3_amd64.deb

tem as dependencias tbm q seguem a mesma parada.

**Comment by huguitovi** [comment]
Buenas Welton, tu solución no funciona en Debian 10 Buster, parece que el sistema rechaza sus dependencias y la termina por desinstalar.

**Comment by ghost** [comment]
como não? funciona sim, antes eu usava no debian 10. mostre o erro que deu e em qual pacote deu o erro.

**Comment by huguitovi** [comment]
$ **sudo dpkg -i gir1.2-webkit-3.0_2.4.11-3_amd64.deb** 
[sudo] password for debian10: 
Seleccionando el paquete gir1.2-webkit-3.0:amd64 previamente no seleccionado.
(Leyendo la base de datos ... 246780 ficheros o directorios instalados actualmente.)
Preparando para desempaquetar gir1.2-webkit-3.0_2.4.11-3_amd64.deb ...
Desempaquetando gir1.2-webkit-3.0:amd64 (2.4.11-3) ...
dpkg: problemas de dependencias impiden la configuración de gir1.2-webkit-3.0:amd64:
 gir1.2-webkit-3.0:amd64 depende de gir1.2-javascriptcoregtk-3.0 (= 2.4.11-3); sin embargo:
  El paquete 'gir1.2-javascriptcoregtk-3.0' no está instalado.
 gir1.2-webkit-3.0:amd64 depende de libjavascriptcoregtk-3.0-0 (>= 1.5.1); sin embargo:
  El paquete 'libjavascriptcoregtk-3.0-0' no está instalado.
 gir1.2-webkit-3.0:amd64 depende de libwebkitgtk-3.0-0 (>= 2.4.6); sin embargo:
  El paquete 'libwebkitgtk-3.0-0' no está instalado.

dpkg: error al procesar el paquete gir1.2-webkit-3.0:amd64 (--install):
 problemas de dependencias - se deja sin configurar
Se encontraron errores al procesar:
 gir1.2-webkit-3.0:amd64


::::entonces:::

$ **sudo apt upgrade**
Leyendo lista de paquetes... Hecho
Creando árbol de dependencias       
Leyendo la información de estado... Hecho
Tal vez quiera ejecutar «apt --fix-broken install» para corregirlo.
Los siguientes paquetes tienen dependencias incumplidas:
 gir1.2-webkit-3.0 : Depende: gir1.2-javascriptcoregtk-3.0 (= 2.4.11-3) pero no está instalado
                     Depende: libjavascriptcoregtk-3.0-0 (>= 1.5.1) pero no está instalado
                     Depende: libwebkitgtk-3.0-0 (>= 2.4.6) pero no está instalado
E: Dependencias incumplidas. Intente «**apt --fix-broken install**» sin paquetes (o especifique una solución).

 ::::entonces:::

**sudo apt --fix-broken install**
Leyendo lista de paquetes... Hecho
Creando árbol de dependencias       
Leyendo la información de estado... Hecho
Corrigiendo dependencias... Listo
Los siguientes paquetes se ELIMINARÁN:
  gir1.2-webkit-3.0
0 actualizados, 0 nuevos se instalarán, 1 para eliminar y 0 no actualizados.
1 no instalados del todo o eliminados.
Se liberarán 444 kB después de esta operación.
¿Desea continuar? [S/n] **S**
(Leyendo la base de datos ... 246784 ficheros o directorios instalados actualmente.)
Desinstalando gir1.2-webkit-3.0:amd64 (2.4.11-3) ...

 ::::entonces:::

**sudo aptitude install  gir1.2-javascriptcoregtk-3.0 libjavascriptcoregtk-3.0-0 libwebkitgtk-3.0-0**

.....
     Mantener los paquetes siguientes en la versión actual:    
1)     gir1.2-javascriptcoregtk-3.0 [Sin instalar]             
2)     gstreamer0.10-plugins-good [Sin instalar]               
3)     libtag1-vanilla [Sin instalar]                          
4)     libtag1c2a [Sin instalar]                               
5)     libwebkitgtk-3.0-0 [Sin instalar]                       

     Leave the following dependencies unresolved:              
6)     libwebkitgtk-3.0-0 recomienda gstreamer0.10-plugins-good
¿Acepta esta solución? [Y/n/q/?] **Y**
Se instalarán los siguiente paquetes NUEVOS:
  libjavascriptcoregtk-3.0-0 
0 paquetes actualizados, 1 nuevos instalados, 0 para eliminar y 0 sin actualizar.
Necesito descargar 1.005 kB de ficheros. Después de desempaquetar se usarán 3.911 kB.
¿Quiere continuar? [Y/n/?] y
Des: 1 http://archive.debian.org/debian wheezy/main amd64 libjavascriptcoregtk-3.0-0 amd64 1.8.1-3.4 [1.005 kB]
Descargados 1.005 kB en 3s (340 kB/s)                 
Seleccionando el paquete libjavascriptcoregtk-3.0-0 previamente no seleccionado.
(Leyendo la base de datos ... 246780 ficheros o directorios instalados actualmente.)
Preparando para desempaquetar .../libjavascriptcoregtk-3.0-0_1.8.1-3.4_amd64.deb ...
Desempaquetando libjavascriptcoregtk-3.0-0 (1.8.1-3.4) ...
Configurando libjavascriptcoregtk-3.0-0 (1.8.1-3.4) ...


 ::::entonces:::

luego ya solo me ofrece desinstalar cosas escenciales para instalar laas dependencias

**Comment by ghost** [comment]
vc precisa instalar os pacotes dependentes do debian stretch.

exemplo:

PACOTE 1:

Erro: gir1.2-webkit-3.0:amd64 depende de gir1.2-javascriptcoregtk-3.0 (= 2.4.11-3); sin embargo:

o que fazer?

baixar http://ftp.br.debian.org/debian/pool/main/w/webkitgtk/gir1.2-javascriptcoregtk-3.0_2.4.11-3_amd64.deb

sudo dpkg -i gir1.2-javascriptcoregtk-3.0_2.4.11-3_amd64.deb



PACOTE 2:

erro: gir1.2-webkit-3.0:amd64 depende de libjavascriptcoregtk-3.0-0 (>= 1.5.1); sin embargo:

o que fazer?

baixar http://ftp.br.debian.org/debian/pool/main/w/webkitgtk/libjavascriptcoregtk-3.0-0_2.4.11-3_amd64.deb

sudo dpkg -i libjavascriptcoregtk-3.0-0_2.4.11-3_amd64.deb



PACOTE 3: 

erro: gir1.2-webkit-3.0:amd64 depende de libwebkitgtk-3.0-0 (>= 2.4.6); sin embargo:

o que fazer?

baixar http://ftp.br.debian.org/debian/pool/main/w/webkitgtk/libjavascriptcoregtk-3.0-0_2.4.11-3_amd64.deb

sudo dpkg -i libjavascriptcoregtk-3.0-0_2.4.11-3_amd64.deb


e assim por diante.

**Comment by huguitovi** [comment]
Segui tus indicaciones, gracias @wellton, realice este **script** para descargar e instalar todas las necesarias en Debian Buster

::::entonces:::

### script for all dependencies on Debian Buster (10)

`wget -i http://ftp.us.debian.org/debian/pool/main/i/icu/libicu57_57.1-6+deb9u4_amd64.deb`
`wget -i http://ftp.us.debian.org/debian/pool/main/libw/libwebp/libwebp5_0.4.1-1.2+b2_amd64.deb`
`wget -i http://ftp.us.debian.org/debian/pool/main/w/webkitgtk/libwebkitgtk-3.0-common_2.4.9-1~deb8u1_all.deb`
`wget -i http://ftp.us.debian.org/debian/pool/main/w/webkitgtk/libjavascriptcoregtk-3.0-0_2.4.9-1~deb8u1_amd64.deb`
`wget -i http://ftp.us.debian.org/debian/pool/main/w/webkitgtk/libwebkitgtk-3.0-0_2.4.9-1~deb8u1_amd64.deb`
`wget -i http://ftp.us.debian.org/debian/pool/main/w/webkitgtk/gir1.2-javascriptcoregtk-3.0_2.4.11-3_amd64.deb`
`wget -i http://ftp.us.debian.org/debian/pool/main/w/webkitgtk/gir1.2-webkit-3.0_2.4.11-3_amd64.deb`
`sudo dpkg -i libicu57_57.1-6+deb9u4_amd64.deb `
`sudo echo "deb http://security.debian.org/debian-security jessie/updates main" >> /etc/apt/sources.list`
`sudo apt update && sudo apt upgrade -y`
`sudo apt install libicu52`
`sudo dpkg -i libwebp5_0.4.1-1.2+b2_amd64.deb `
`sudo dpkg -i libwebkitgtk-3.0-common_2.4.9-1~deb8u1_all.deb `
`sudo dpkg -i libjavascriptcoregtk-3.0-0_2.4.9-1~deb8u1_amd64.deb `
`sudo dpkg -i libwebkitgtk-3.0-0_2.4.9-1~deb8u1_amd64.deb `
`sudo dpkg -i gir1.2-javascriptcoregtk-3.0_2.4.11-3_amd64.deb `
`sudo dpkg -i gir1.2-webkit-3.0_2.4.11-3_amd64.deb `

::::entonces:::
 
**`$ sudo apt-get install git gettext python3-mako gir1.2-notify-0.7 python3-lxml python3-gi-cairo python3-cairo gstreamer1.0-plugins-ugly gstreamer1.0-plugins-good gstreamer1.0-plugins-bad rhythmbox-plugins gir1.2-webkit-3.0`**

`Leyendo lista de paquetes... Hecho`
`Creando árbol de dependencias       `
`Leyendo la información de estado... Hecho`
`gettext ya está en su versión más reciente (0.19.8.1-9).`
`git ya está en su versión más reciente (1:2.20.1-2+deb10u3).`
`gstreamer1.0-plugins-bad ya está en su versión más reciente (1.14.4-1+b1).`
`gstreamer1.0-plugins-good ya está en su versión más reciente (1.14.4-1).`
`gstreamer1.0-plugins-ugly ya está en su versión más reciente (1.14.4-1).`
`gir1.2-notify-0.7 ya está en su versión más reciente (0.7.7-4).`
`python3-lxml ya está en su versión más reciente (4.3.2-1).`
`python3-mako ya está en su versión más reciente (1.0.7+ds1-1).`
`python3-cairo ya está en su versión más reciente (1.16.2-1+b1).`
`python3-gi-cairo ya está en su versión más reciente (3.30.4-1).`
`rhythmbox-plugins ya está en su versión más reciente (3.4.3-2).`
`gir1.2-webkit-3.0 ya está en su versión más reciente (2.4.11-3).`
`0 actualizados, 0 nuevos se instalarán, 0 para eliminar y 1 no actualizados.`

::::entonces:::
Perfecto, todo se deja instalar 

**`$ rm -rf ~/.local/share/rhythmbox/plugins/coverart_browser`
`$ git clone https://github.com/fossfreedom/coverart-browser.git`
`$ cd coverart-browser`
`$ ./install.sh`**


`installing languages to /usr/share/locale/`
`installing es`
`Installing the glib schema (password needed)`

ahora voy a Ryhthmbox

![Captura de pantalla de 2020-08-19 23-39-27](https://user-images.githubusercontent.com/52084755/90710818-8ba32f80-e275-11ea-975a-ee09f416dcf1.png)
![Captura de pantalla de 2020-08-19 23-39-40](https://user-images.githubusercontent.com/52084755/90710820-8cd45c80-e275-11ea-98fa-304d4220e349.png)


dont work... Sigue sin funcionar, ahora si que no se que es lo que no funciona. 🤔 
(ToT)/~~~

**Comment by ghost** [comment]
você modificou as variáveis?

https://github.com/fossfreedom/coverart-browser/commit/f8562992d9170599d04da8764422a9fe19ed6fa1

**Comment by ghost** [comment]
isso se resume a:

nano -c ~/.local/share/rhythmbox/plugins/coverart_browser/coverart_album.py

modifique as linhas 1590 e 1591 

disso:
async = rb.Loader()
async.get_url(uri, cover_update, coverobject)

para isso:
asyncLoader = rb.Loader()
asyncLoader.get_url(uri, cover_update, coverobject)

**Comment by huguitovi** [comment]
Mi gran amigo @wellton cambie isso pero no funciono... 

mi solucion fue simple, cansado de la lucha, a esta altura:::

### `sudo apt-get install quodlibet`

y listo
![Captura de pantalla de 2020-08-20 23-24-39](https://user-images.githubusercontent.com/52084755/90845833-40ecea80-e33d-11ea-8b0a-effad43b9336.png)


para ti que falas português, agora ouço as Mamonas Assassinas, nuevamente ... Muchas gracias!
