### ISSUE TITLE
covre art browser doesnt work

### ISSUE THREAD

**Issue by linuxitomio** [fossfreedom/coverart-browser#405]
here I attach when I try to click in cover browser plugin:

$ rhythmbox
(rhythmbox:15186): Gtk-WARNING **: 21:35:34.875: actionhelper: action app.play-repeat can't be activated due to parameter type mismatch (parameter type NULL, target type b)
(rhythmbox:15186): Gtk-WARNING **: 21:35:34.875: actionhelper: action app.play-shuffle can't be activated due to parameter type mismatch (parameter type NULL, target type b)
(rhythmbox:15186): Gtk-WARNING **: 21:35:35.218: Theme parsing error: :2:36: The style property GtkCheckButton:indicator-spacing is deprecated and shouldn't be used anymore. It will be removed in a future version
** (rhythmbox:15186): WARNING **: 21:35:44.045: Error importing plugin 'coverart_browser':
Traceback (most recent call last):
File "/usr/lib/python3.8/importlib/init.py", line 127, in import_module
return _bootstrap._gcd_import(name[level:], package, level)
File "", line 1014, in _gcd_import
File "", line 991, in _find_and_load
File "", line 975, in _find_and_load_unlocked
File "", line 671, in _load_unlocked
File "", line 783, in exec_module
File "", line 219, in _call_with_frames_removed
File "/home/deloco/.local/share/rhythmbox/plugins/coverart_browser/coverart_browser.py", line 32, in 
from coverart_browser_source import CoverArtBrowserSource
File "/home/deloco/.local/share/rhythmbox/plugins/coverart_browser/coverart_browser_source.py", line 33, in 
from coverart_album import AlbumManager
File "/home/deloco/.local/share/rhythmbox/plugins/coverart_browser/coverart_album.py", line 1590
async = rb.Loader()
^
SyntaxError: invalid syntax
(rhythmbox:15186): libpeas-WARNING **: 21:35:44.045: Error loading plugin 'coverart_browser'
/usr/lib/python3/dist-packages/gi/overrides/GObject.py:502: Warning: ../../../gobject/gsignal.c:2735: instance '0x563def745ee0' has no handler with id '14742'
return func(*args, **kwargs)
/usr/lib/python3/dist-packages/gi/overrides/GObject.py:502: Warning: ../../../gobject/gsignal.c:2735: instance '0x563def745ee0' has no handler with id '14741'
return func(*args, **kwargs)
(rhythmbox:15186): Gtk-WARNING **: 21:35:57.834: Can't set a parent on widget which has a parent

**Comment by fossfreedom** [comment]
Duplicate https://github.com/fossfreedom/coverart-browser/issues/404

**Comment by linuxitomio** [comment]
thanks for your answer. But that issue number 404 doesnt work for m cause I am using Ubuntu 20.04

**Comment by ghost** [comment]
> thanks for your answer. But that issue number 404 doesnt work for m cause I am using Ubuntu 20.04

Make this:

sudo nano /etc/apt/sources.list

write this:
deb [trusted=yes] http://ftp.de.debian.org/debian stretch main

ctrl+o, enter, ctrl+x

sudo apt update

sudo apt-get install git gettext python3-mako gir1.2-notify-0.7 python3-lxml python3-gi-cairo python3-cairo gstreamer1.0-plugins-ugly gstreamer1.0-plugins-good gstreamer1.0-plugins-bad rhythmbox-plugins gir1.2-webkit-3.0

rm -rf ~/.local/share/rhythmbox/plugins/coverart_browser
git clone https://github.com/fossfreedom/coverart-browser.git
cd coverart-browser
./install.sh

**Comment by linuxitomio** [comment]
hello wellton.

Is ths specific for Ubuntu?? 
I have also try in a Debian buster distro and it doesnt either work??

**Comment by linuxitomio** [comment]
and where should I write this one:

deb [trusted=yes] http://ftp.de.debian.org/debian stretch main

**Comment by ghost** [comment]
hello Linuxitomio. put this in place of the debian repository

 echo "deb http://de.archive.ubuntu.com/ubuntu/ bionic main universe" | sudo tee -a /etc/apt/sources.list

**Comment by ghost** [comment]
Its to ubuntu 20.04

**Comment by linuxitomio** [comment]
it doesnt work
rhythmbox

(rhythmbox:2675): Gtk-WARNING **: 20:18:44.767: actionhelper: action app.play-repeat can't be activated due to parameter type mismatch (parameter type NULL, target type b)

(rhythmbox:2675): Gtk-WARNING **: 20:18:44.767: actionhelper: action app.play-shuffle can't be activated due to parameter type mismatch (parameter type NULL, target type b)

(rhythmbox:2675): libpeas-WARNING **: 20:19:12.259: Could not find plugin 'coverart_search_providers' for plugin 'coverart_browser'
/usr/lib/python3/dist-packages/gi/overrides/GObject.py:502: Warning: ../../../gobject/gsignal.c:2735: instance '0x55c66b496e40' has no handler with id '13666'
  return func(*args, **kwargs)
/usr/lib/python3/dist-packages/gi/overrides/GObject.py:502: Warning: ../../../gobject/gsignal.c:2735: instance '0x55c66b496e40' has no handler with id '13665'
  return func(*args, **kwargs)

(rhythmbox:2675): Gtk-WARNING **: 20:19:17.013: Can't set a parent on widget which has a parent

(rhythmbox:2675): RhythmDB-CRITICAL **: 20:19:17.144: rb_refstring_ref: assertion 'g_atomic_int_get (&val->refcount) > 0' failed

(rhythmbox:2675): RhythmDB-CRITICAL **: 20:19:17.144: rb_refstring_ref: assertion 'g_atomic_int_get (&val->refcount) > 0' failed

(rhythmbox:2675): RhythmDB-CRITICAL **: 20:19:17.144: rb_refstring_ref: assertion 'g_atomic_int_get (&val->refcount) > 0' failed

(rhythmbox:2675): RhythmDB-CRITICAL **: 20:19:17.144: rb_refstring_ref: assertion 'g_atomic_int_get (&val->refcount) > 0' failed
corrupted double-linked list
Aborted (core dumped)


and seems that the update wanna update everything

**Comment by ghost** [comment]
it doesn't work because you didn't install the coverart_search_providers plugin.

it needs to be installed first, as per the documentation.

"Note 1 - the CoverArt Browser plugin also requires installing the following plugin:

    https://github.com/fossfreedom/coverart-search-providers
"

**Comment by linuxitomio** [comment]
waowww Wellton. U are just the king man. Seems that it works. And what should I do with Ubuntu trying to upgrade the webkit?

and another thing, why dont you help Rhythmbox people to make this working without the need of a plugin, where it can just be installed allready in the program?
you rock man

**Comment by linuxitomio** [comment]
When clicking in the cover art , it displays a grey speaker, but not the real cover from the jpg

**Comment by ghost** [comment]
Hello, I am not the owner of the program, I only contribute to try to make it work on debian and ubuntu but it is not ideal yet because it needs an old package. The real Rock man is @fossfreedom  (David Mohammed)

But it would be very interesting for Rhythmbox to include this plugin by default.

You need to play any song on the album once for the cover to appear, if it does not appear, you will have to download it manually, but the normal thing is to already appear if you have the folder.jpg in the album folder or if it is already inside the audio file .

**Comment by linuxitomio** [comment]
yes of course, fossfreedom is the father!! 

thanks wellton

**Comment by ghost** [comment]
you are welcome =)
