### ISSUE TITLE
Installation of coverart-browser

### ISSUE THREAD

**Issue by anlin01** [fossfreedom/coverart-browser#410]
First of all, thank you for this extension and the work with it.
I am quite new to linux (using ubuntu 20.04 LTS) and try to figure out how to install the extension "coverart-browser" for Rhythmbox.

I executed "rm -rf ~/.local/share/rhythmbox/plugins/coverart_browser" - this directory was not existing anyway.
Then "git clone https://github.com/fossfreedom/coverart-browser.git"  this worked fine.
"cd coverart-browser" - ok
"./install.sh" - There I got the following message:

_____________________________________
~/coverart-browser$ ./install.sh
installing languages to /usr/share/locale/
installing de
./lang.sh: 15: msgfmt: not found
Installing the glib schema (password needed)
_____________________________________

That is all.

When executing "sudo apt-get install git gettext python3-mako gir1.2-notify-0.7 python3-lxml python3-gi-cairo python3-cairo gstreamer1.0-plugins-ugly gstreamer1.0-plugins-good gstreamer1.0-plugins-bad rhythmbox-plugins gir1.2-webkit-3.0"

the terminal deliveres a message that the packages "gir1.2-webkit-3.0" could not be found.

What can I do?

Thank you,
André

**Comment by ghost** [comment]
Hi.

make this:

echo "deb http://de.archive.ubuntu.com/ubuntu/ bionic main universe" | sudo tee -a /etc/apt/sources.list

sudo apt update

execute the same command:

sudo apt-get install git gettext python3-mako gir1.2-notify-0.7 python3-lxml python3-gi-cairo python3-cairo gstreamer1.0-plugins-ugly gstreamer1.0-plugins-good gstreamer1.0-plugins-bad rhythmbox-plugins gir1.2-webkit-3.0

att

**Comment by anlin01** [comment]
Thank you so much for your quick answer! The installation was finished successfully.

I guess the plugin must be activated. When I open the settings, and from there the tab "plugins", the "CoverArt Browser" is displayed. When I select this plugin, the checkbox disappears and a small exclamation mark appears, see the pdf with screenshots:

[Rhythmbox-Settings Plugins.pdf](https://github.com/fossfreedom/coverart-browser/files/5798157/Rhythmbox-Settings.Plugins.pdf)

Do you have an idea what to do here?

André

**Comment by ghost** [comment]
open the terminal, type rhythmbox and copy and paste what appears here, ok?

**Comment by anlin01** [comment]
The following appears (while rhythmbox starts):

(rhythmbox:7268): Gtk-WARNING **: 21:55:40.163: actionhelper: action app.play-repeat can't be activated due to parameter type mismatch (parameter type NULL, target type b)

(rhythmbox:7268): Gtk-WARNING **: 21:55:40.163: actionhelper: action app.play-shuffle can't be activated due to parameter type mismatch (parameter type NULL, target type b)

**Comment by ghost** [comment]
only that ? without any error? strange ... I don't know what it is because the errors were supposed to appear there.

**Comment by anlin01** [comment]
One more line when I close rhythmbox:

(rhythmbox:7679): Gtk-WARNING **: 22:06:52.076: actionhelper: action app.play-repeat can't be activated due to parameter type mismatch (parameter type NULL, target type b)

(rhythmbox:7679): Gtk-WARNING **: 22:06:52.076: actionhelper: action app.play-shuffle can't be activated due to parameter type mismatch (parameter type NULL, target type b)

(rhythmbox:7679): Gtk-WARNING **: 22:06:56.036: Can't set a parent on widget which has a parent

**Comment by ghost** [comment]
ok, do the following.

rm -Rf ~/.local/share/rhythmbox/plugins/coverart_*

and redo the plugin installation.



(use the this code - https://github.com/fossfreedom/coverart-browser)

remember: install this before: https://github.com/fossfreedom/coverart-search-providers

**Comment by anlin01** [comment]
Ok, first the installation of "https://github.com/fossfreedom/coverart-search-providers":

_____
rm -rf ~/.local/share/rhythmbox/plugins/coverart_search_providers
git clone https://github.com/fossfreedom/coverart-search-providers.git
cd coverart-search-providers
./install.sh
________

The output is:
~/coverart-search-providers$ ./install.sh
installing languages to /usr/share/locale/
no en.po to install
Installing the glib schema (password needed)

I am not sure if this is fine.

Installation of "https://github.com/fossfreedom/coverart-search-providers":

________________
git clone https://github.com/fossfreedom/coverart-browser.git
cd coverart-browser
./install.sh
________________

The output is:
installing languages to /usr/share/locale/
installing en_US
en_US.po:13: warning: header field 'Language-Team' still has the initial default value
Installing the glib schema (password needed)

I am not sure if this if fine. 

But the cover arts are displayed!

**Comment by ghost** [comment]
Show. =) its works. =)

**Comment by anlin01** [comment]
Thank you so much for your wonderful help!
Just a small issue, if I may ask:
Not all CoverArts are loaded, some or a lot are left out. When I click on each CoverArt, the first song is played, and the CoverArt is loaded. I have to click on each that it is loaded. See attached picture. Do you have an idea what I could do?

[CoverArt.pdf](https://github.com/fossfreedom/coverart-browser/files/5798532/CoverArt.pdf)

**Comment by ghost** [comment]
You are welcome =)

yes, you will need to play some music from each album to appear. I don't know how to fix this. Maybe the @fossfreedom (David Mohammed) knows.

att

**Comment by anlin01** [comment]
I say thank you! :)

If I may ask a last question (2 questions) ?:

There are the following plugins installed:
- CoverArt Browser
- CoverArt Browser Search Providers
- CoverArt Search

"CoverArt Browser Search Providers" replaces the "CoverArt Search". So both first must be activated, right?

Then:
The library Location (tab "Music") contains the folder where the music files are placed in.
In my case it is ~/Music/Musicfiles/
The CoverArt displays CoverArts from other folders, for example ~/Music/Music_left_to_import/
This folder does not belong to the folder which rhythmbox uses. 
Maybe the plugin searches for all files below ~/Music/ ?

**Comment by ghost** [comment]
I think that's it. I don't know how to solve it.

**Comment by anlin01** [comment]
Thank you very much for your kind help!
